### ISSUE TITLE
Implement JumpQueue Feature

### ISSUE THREAD

**Issue by MichaelHHall** [JOBBIN9422/TerminusDotNET#24]
It would be nice to be able to force an item to the front of the music queue. This would include a base function that would put a song at the top of the queue, and include functions to add a song directly to the top of the queue (eg "!playnow" or !ytnow" that adds a song to the front and playnexts) and to move a song from the queue to the front (eg "!queuejump 22" puts item 22 in the queue into spot one). 

Once this feature is implemented, it could be used in the weed function and could make the "backup queue" object obsolete, which would be a nice bit of optimization for the garbage code I wrote.

**Comment by ct-bess** [comment]
neat

**Comment by JOBBIN9422** [comment]
We'll have to change the underlying data structure used for the song queue. ConcurrentQueue doesn't support that level of control (you can pretty much only use standard queue operations). 

I changed it to a linked list on my private branch and can insert songs at the front of the queue without any issue.

**Comment by JOBBIN9422** [comment]
Done (check the help for yt, play, playlist, and qfront)
