### ISSUE TITLE
Optimize weed scheduler

### ISSUE THREAD

**Issue by MichaelHHall** [JOBBIN9422/TerminusDotNET#25]
I don't even know where to start with this one. The whole set of code is garbage, but the low hanging fruit for optimizing this is setting it up to jumpqueue (after #24 is finished) and removing the backupqueue, so it fits more elegantly in the audio system instead of being some crappy black sheep I made as a meme. Bonus would be optimizing the scheduling system somehow, but I don't have an idea of how that's possible.

**Comment by JOBBIN9422** [comment]
Done (1593bacb20be1ed92442584b9f23d59aedbbf925)
