### ISSUE TITLE
Hard Coded IP Address

### ISSUE THREAD

**Issue by ct-bess** [JOBBIN9422/TerminusDotNET#28]
This shouldn't be here, this is someone's IP :thinking: 

https://github.com/JOBBIN9422/TerminusDotNET/blob/436ab71597a7d7208a6be0ca4fea1d13d572ff8a/Modules/PingModule.cs#L30

Sensitive data exposure BTW

**Comment by JOBBIN9422** [comment]
Fixed via 1e1b410
