### ISSUE TITLE
URL Injection vulnerability

### ISSUE THREAD

**Issue by ct-bess** [JOBBIN9422/TerminusDotNET#29]
Parameterize the query string parameters so that the user cant query for something other than `ticker`

https://github.com/JOBBIN9422/TerminusDotNET/blob/436ab71597a7d7208a6be0ca4fea1d13d572ff8a/Helpers/StonksHelper.cs#L18

e.g. prevent this case `!stonks TSLA&otherParam=true`

[Reference](https://owasp.org/www-community/attacks/Code_Injection)

**Edit:**

~~Found another one~~ nvm this one is no cause for concern

https://github.com/JOBBIN9422/TerminusDotNET/blob/436ab71597a7d7208a6be0ca4fea1d13d572ff8a/Services/AudioService.cs#L525

**Comment by JOBBIN9422** [comment]
Fixed via 061c5e4
