### ISSUE TITLE
Terminus Radio

### ISSUE THREAD

**Issue by ct-bess** [JOBBIN9422/TerminusDotNET#32]
:b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: 

### Motivation

There are plenty of times where people don't possess the brain processing power to come up with *good* songs to add to the queue. The `!playlist` and `!hideki` commands are steps in the right direction, but this `!radio` command could be the true remedy.

### Abstract

The `!hideki` command got me thinking it would be real neet if we could curate playlist(s) for Terminus to pull songs from.
I don't think users can be added as collaberators to a YouTube playlist, so here's a couple of ways around this:

1. There is 1 playlist that Terminus uses; 1 person adds songs to it that members request.

   This method will require more manual intervention to update the playlist, but less *questionable* songs will be added.

2. There are many member created playlists for Terminus to use

   This method will be more seamless but requires more work to pull off

#### Sample Command Usage

The following commands work for both implementations:

- `!radio` displays some usage information
- `!radio continuous` plays random songs from the playlist(s) continuously for a while :tm:
- `!radio rand` plays a random song from the playlist(s)
- `!radio 69` plays the 69th song in the playlist(s) (if it exists)
- `!radio play "hideki naganuma"` plays the 1st song whos title contains `hideki naganuma`
- `!radio find "hideki naganuma"` displays all songs whos title contains `hideki naganuma`
- `!radio playlists` display all playlists that are being used

The following commands require the many playlists for each member implementation:

- `!radio rand @user` plays a random song from `@user`'s playlist
- `!radio 69 @user` plays the 69th song in `@user`'s playlist (if it exists)
- `!radio play "hideki naganuma" @user` plays the 1st song whos title contains `hideki naganuma` from `@user`'s playlist
- `!radio find "hideki naganuma" @user` displays all songs whos title contains `hideki naganuma` from `@user`'s playlist
- `!radio update @user https://playlist-url` update `@user`'s playlist to the given URL; Even if `@user` has no playlist

#### Other Thoughts

- `@user` portion could also accept `me` to pull from the message author's playlist
- `@user` could be substituted for a username to avoid notifying the at-ed user when someone runs this command
- `play` could be the subcommand to play a song to keep things consistent

   e.g. `!radio play 69`, `!radio play "grant macdonald"`, `!radio play rand`

- Would be nice if we could add multiple random songs like `!radio rand 5` to add 5 random songs

   This should be limited to adding no more than 5 or 10 songs

:b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b: :b:

**Comment by JOBBIN9422** [comment]
THIS IS kinda DONE

SHUCKS DANG THNX FOR YOUR IDEA

LOVE MY SUPERCOOL FANS
