### ISSUE TITLE
Initial D Image command

### ISSUE THREAD

**Issue by ct-bess** [JOBBIN9422/TerminusDotNET#41]
Might be funny to plop this on top of an image, much like `!morrowind` and `!dmc` but with a giant picture of Keiskue and his RX7 witnessing the inertia drift
![inertia-drift-template](https://user-images.githubusercontent.com/32228296/118319544-88fdff80-b4c0-11eb-82c1-9c549aa02920.png)

**Comment by insyri** [comment]
remove black bars on hand sides(?)
![image](https://user-images.githubusercontent.com/60794909/118839587-9c301700-b894-11eb-809a-c64b7bbb06b8.png)

**Comment by ct-bess** [comment]
Very Good Point! @jasmine pls use insyri's edit thanks i see road man

**Comment by MichaelHHall** [comment]
ok

**Comment by JOBBIN9422** [comment]
done ok

**Comment by ct-bess** [comment]
i am very much interested but the thing is that agreed thank you
